---
title: "for_michelle"
author: "Ana Miller-ter Kuile"
date: "5/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(readxl)
```


Import datasets of DNA read counts, and then subset only the Pantala flavescens and Neoscona theisi sequences from this:

```{r}
ASV1 <- read.delim(here("data", "zotu_table_h.txt"), sep = '\t')
ASV1$X.OTU.ID <- as.character(ASV1$X.OTU.ID)

ASV2 <- read.delim(here("data", "zotu_table_j.txt"), sep = '\t')
ASV2$X.OTU.ID <- as.character(ASV2$X.OTU.ID)

data <- ASV1 %>%
  left_join(ASV2, by = "X.OTU.ID") %>%
  gather(sample, reads, ISO16:PHH042) %>%
  filter(reads > 0) 

data <- data[str_detect(data$sample, "PAN") |
               str_detect(data$sample, "NEO"),]
```

Import both NCBI and BOLD taxonomic assignments for prey:

```{r}
IDs_ncbi <- read.csv(here("data", "taxonomies", "NCBI", "ID.csv"))
IDs_ncbi <- IDs_ncbi %>%
  rename("ID_ncbi" = "ID")

bold1 <- read.csv(here("data", "taxonomies", "BOLD", "01.csv"))
bold2 <- read.csv(here("data", "taxonomies", "BOLD", "100.csv"))
bold3 <- read.csv(here("data", "taxonomies", "BOLD", "200.csv"))
bold4 <- read.csv(here("data", "taxonomies", "BOLD", "300.csv"))
bold5 <- read.csv(here("data", "taxonomies", "BOLD", "400.csv"))
bold6 <- read.csv(here("data", "taxonomies", "BOLD", "500.csv"))
bold7 <- read.csv(here("data", "taxonomies", "BOLD", "600.csv"))
bold8 <- read.csv(here("data", "taxonomies", "BOLD", "700.csv"))
bold9 <- read.csv(here("data", "taxonomies", "BOLD", "800.csv"))
bold10 <- read.csv(here("data", "taxonomies", "BOLD", "900.csv"))
bold11 <- read.csv(here("data", "taxonomies", "BOLD", "1000.csv"))
bold12 <- read.csv(here("data", "taxonomies", "BOLD", "1100.csv"))
bold13 <- read.csv(here("data", "taxonomies", "BOLD", "1200.csv"))

IDs_bold <- bold1 %>%
  bind_rows(bold2) %>%
  bind_rows(bold3) %>%
  bind_rows(bold4) %>%
  bind_rows(bold5) %>%
  bind_rows(bold6) %>%
  bind_rows(bold7) %>%
  bind_rows(bold8) %>%
  bind_rows(bold9) %>%
  bind_rows(bold10) %>%
  bind_rows(bold11) %>%
  bind_rows(bold12) %>%
  bind_rows(bold13) %>%
  select(Query.ID, Best.ID) %>%
  filter(!Best.ID == "No match") %>%
  rename("ID_bold" = "Best.ID", "ZOTU" = "Query.ID")

IDs <- IDs_ncbi %>%
  full_join(IDs_bold, by = "ZOTU")
```

```{r}
preds <- data %>%
  rename("ZOTU" = "X.OTU.ID") %>%
  left_join(IDs, by = "ZOTU")

preds$ID_ncbi <- as.character(preds$ID_ncbi)
preds$ID_bold <- as.character(preds$ID_bold)
preds$prey_ID <- ifelse(is.na(preds$ID_bold), preds$ID_ncbi, preds$ID_bold)

preds <- preds %>%
  mutate(prey_ID = ifelse(prey_ID == "2012", "Oxya japonica", 
                          ifelse(prey_ID == "2017", "Suidasia", prey_ID)))

preds <- preds %>% 
  dplyr::mutate(pred_ID=ifelse(str_detect(sample, "PAN"),"Pantala flavescens","Neoscona theisi"))

pred_sp <- preds %>%
  group_by(sample, prey_ID, pred_ID) %>%
  summarise(reads = sum(reads)) %>%
  group_by(pred_ID, prey_ID) %>%
  summarise(presence = n(), abundance = sum(reads)) %>%
  mutate(sample_size = ifelse(pred_ID == "Pantala flavescens", 15, 26))
```


